import type { NextPage } from 'next';
import { useAccount, useConnect, useDisconnect } from 'wagmi'
import Explain from '../components/Explain';
import Header from '../components/Header';
import Mint from '../components/Mint';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {

  const { address, isConnected } = useAccount()

  return (
    <div className={styles.container}>
      <title>Clu3</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
      <Header/>
      {!isConnected ? (
        <>
        <Explain />
        </>
      ):(
        <div className={styles.main}>
          <div style={{"justifyContent":"center"}}>
          <div className={styles.card}>
          <h3 style={{'textAlign':'center'}}>Welcome to clu3🤖!</h3>
          <p>Get Clu to get rid of the undesired bots putting hands on your smart contract!</p>
          </div>
          <Mint/>
          </div>
        
          
        </div>
      )}
      
      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at Clu3🤖
        </a>
      </footer>
    </div>
  );
};

export default Home;
